extends Node

var card_resource_path_dict : Dictionary = {
	# Base Set
	"Dean Thomas" : "res://cards/base_set/resources/001-Base-DeanThomas.tres",
	#"Draco Malfoy" : "res://cards/base_set/resources/002-Base-DracoMalfoy.tres",
	"Draco Malfoy" : "res://cards/base_set/resources/003-Base-DracoMalfoy.tres",
	"Dragon's Escape" : "res://cards/base_set/resources/004-Base-DragonsEscape.tres",
	"Elixir of Life" : "res://cards/base_set/resources/005-Base-ElixirOfLife.tres",
	"Gringotts' Cart Ride" : "res://cards/base_set/resources/006-Base-GringottsCartRide.tres",
	"Hannah Abbott" : "res://cards/base_set/resources/007-Base-HannahAbbott.tres",
	"Harry Potter" : "res://cards/base_set/resources/008-Base-HarryPotter.tres",
	#"Hermione Granger" : "res://cards/base_set/resources/009-Base-HermioneGranger.tres",
	"Hermione Granger" : "res://cards/base_set/resources/010-Base-HermioneGranger.tres",
	"Human Chess Game" : "res://cards/base_set/resources/011-Base-HumanChessGame.tres",
	"Invisibility Cloak" : "res://cards/base_set/resources/012-Base-InvisibilityCloak.tres",
	"Nearly Headless Nick" : "res://cards/base_set/resources/013-Base-NearlyHeadlessNick.tres",
	"Obliviate" : "res://cards/base_set/resources/014-Base-Obliviate.tres",
	"Professor Filius Flitwick" : "res://cards/base_set/resources/015-Base-ProfessorFiliusFlitwick.tres",
	"Professor Severus Snape" : "res://cards/base_set/resources/016-Base-ProfessorSeverousSnape.tres",
	"Ron Weasley" : "res://cards/base_set/resources/017-Base-RonWeasley.tres",
	"Rubeus Hagrid" : "res://cards/base_set/resources/018-Base-RubeusHagrid.tres",
	"Troll in the Bathroom" : "res://cards/base_set/resources/019-Base-TrollintheBathroom.tres",
	"Unicorn" : "res://cards/base_set/resources/020-Base-Unicorn.tres",
	"Delivery Owl" : "res://cards/base_set/resources/021-Base-DeliveryOwl.tres",
	"Draught of Living Death" : "res://cards/base_set/resources/022-Base-DraughtOfLivingDeath.tres",
	"Harry Hunting" : "res://cards/base_set/resources/023-Base-HarryHunting.tres",
	"History of Magic" : "res://cards/base_set/resources/024-Base-HistoryOfMagic.tres",
	"Incendio" : "res://cards/base_set/resources/025-Base-Incendio.tres",
	"Malevolent Mixture" : "res://cards/base_set/resources/026-Base-MalevolentMixture.tres",
	"Meet the Centaurs" : "res://cards/base_set/resources/027-Base-MeetTheCentaurs.tres",
	"Mountain Troll" : "res://cards/base_set/resources/028-Base-MountainTroll.tres",
	"Mrs Norris" : "res://cards/base_set/resources/029-Base-MrsNorris.tres",
	"Norbert" : "res://cards/base_set/resources/030-Base-Norbert.tres",
	"Phoenix Feather Wand" : "res://cards/base_set/resources/031-Base-PhoenixFeatherWand.tres",
	"Platform 9 3/4" : "res://cards/base_set/resources/032-Base-Platform934.tres",
	"Potion Ingredients" : "res://cards/base_set/resources/033-Base-PotionIngredients.tres",
	"Raven to Writing Desk" : "res://cards/base_set/resources/034-Base-RavenToWritingDesk.tres",
	"Shrinking Potion" : "res://cards/base_set/resources/035-Base-ShrinkingPotion.tres",
	"Titillando" : "res://cards/base_set/resources/036-Base-Titillando.tres",
	"Transfiguration Exam" : "res://cards/base_set/resources/037-Base-TransfigurationExam.tres",
	"Transfiguration Test" : "res://cards/base_set/resources/038-Base-TransfigurationTest.tres",
	"4 Privet Drive" : "res://cards/base_set/resources/039-Base-4PrivetDrive.tres",
	"Alchemy" : "res://cards/base_set/resources/040-Base-Alchemy.tres",
	"Apothecary" : "res://cards/base_set/resources/041-Base-Apothecary.tres",
	"Apparate" : "res://cards/base_set/resources/042-Base-Apparate.tres",
	"Baby Dragon" : "res://cards/base_set/resources/043-Base-BabyDragon.tres",
	"Bluebell Flames" : "res://cards/base_set/resources/044-Base-BluebellFlames.tres",
	"Burning Bitterroot Balm" : "res://cards/base_set/resources/045-Base-BurningBitterrootBalm.tres",
	"Cage" : "res://cards/base_set/resources/046-Base-Cage.tres",
	"Confundus" : "res://cards/base_set/resources/047-Base-Confundus.tres",
	"Diagon Alley" : "res://cards/base_set/resources/048-Base-DiagonAlley.tres",
	"Dogbreath Potion" : "res://cards/base_set/resources/049-Base-DogbreathPotion.tres",
	"Draco's Trick": "res://cards/base_set/resources/050-Base-DracosTrick.tres",
	"Dragon Heart Wand" : "res://cards/base_set/resources/051-Base-DragonHeartWand.tres",
	"Fumos" : "res://cards/base_set/resources/052-Base-Fumos.tres",
	"Guard Dog" : "res://cards/base_set/resources/053-Base-GuardDog.tres",
	"Hiding From Snape" : "res://cards/base_set/resources/054-Base-HidingFromSnape.tres",
	"Kelpie" : "res://cards/base_set/resources/055-Base-Kelpie.tres",
	"Logic Puzzle" : "res://cards/base_set/resources/056-Base-LogicPuzzle.tres",
	"Mysterious Egg" : "res://cards/base_set/resources/057-Base-MysteriousEgg.tres",
	"Nurture" : "res://cards/base_set/resources/058-Base-Nurture.tres",
	"Ollivanders" : "res://cards/base_set/resources/059-Base-Ollivanders.tres",
	"Peeves Causes Trouble" : "res://cards/base_set/resources/060-Base-PeevesCausesTrouble.tres",
	"Pet Toad" : "res://cards/base_set/resources/061-Base-PetToad.tres",
	"Pomfrey's Pick-Me-Up" : "res://cards/base_set/resources/062-Base-PomfreysPickMeUp.tres",
	"Potions Exam" : "res://cards/base_set/resources/063-Base-PotionsExam.tres",
	"Reptile House" : "res://cards/base_set/resources/064-Base-ReptileHouse.tres",
	"Silver Cauldron" : "res://cards/base_set/resources/065-Base-SilverCauldron.tres",
	"Snuffling Potion" : "res://cards/base_set/resources/066-Base-SnufflingPotion.tres",
	"Stupefy" : "res://cards/base_set/resources/067-Base-Stupefy.tres",
	"Take Root" : "res://cards/base_set/resources/068-Base-TakeRoot.tres",
	"Transmogrify" : "res://cards/base_set/resources/069-Base-Transmogrify.tres",
	"Unusual Pets" : "res://cards/base_set/resources/070-Base-UnusualPets.tres",
	"Vanishing Glass" : "res://cards/base_set/resources/071-Base-VanishingGlass.tres",
	"Winged Keys" : "res://cards/base_set/resources/072-Base-WingedKeys.tres",
	"Accio" : "res://cards/base_set/resources/073-Base-Accio.tres",
	"Avifors" : "res://cards/base_set/resources/074-Base-Avifors.tres",
	"Baubillious" : "res://cards/base_set/resources/075-Base-Baubillious.tres",
	"Boa Constrictor" : "res://cards/base_set/resources/076-Base-BoaConstrictor.tres",
	"Boil Cure" : "res://cards/base_set/resources/077-Base-BoilCure.tres",
	"Borrowed Wand" : "res://cards/base_set/resources/078-Base-BorrowedWand.tres",
	"Cauldron to Sieve" : "res://cards/base_set/resources/079-Base-CauldronToSieve.tres",
	"Curious Raven" : "res://cards/base_set/resources/080-Base-CuriousRaven.tres",
	"Dungbomb" : "res://cards/base_set/resources/081-Base-Dungbomb.tres",
	"Epoximise" : "res://cards/base_set/resources/082-Base-Epoximise.tres",
	"Erumpent Potion" : "res://cards/base_set/resources/083-Base-ErumpentPotion.tres",
	"Fluffy Falls Asleep" : "res://cards/base_set/resources/084-Base-FluffyFallsAsleep.tres",
	"Forest Troll" : "res://cards/base_set/resources/085-Base-ForestTroll.tres",
	"Forgetfulness Potion" : "res://cards/base_set/resources/086-Base-ForgetfullnessPotion.tres",
	"Foul Brew" : "res://cards/base_set/resources/087-Base-FoulBrew.tres",
	"Giant Tarantula" : "res://cards/base_set/resources/088-Base-GiantTarantula.tres",
	"Hagrid and the Stranger" : "res://cards/base_set/resources/089-Base-HagridAndTheStranger.tres",
	"Homework" : "res://cards/base_set/resources/090-Base-Homework.tres",
}

func get_resource_path(cardname: String) -> String:
	return card_resource_path_dict[cardname]
